name: India
gdp: 1000000
health_resource_stockpile: 500.0
sanitation_equipment_stockpile: 20.0
human_welfare_resource: 100.0
happiness_index: 1.0
procedure_resistance: 0.6
cleanliness_index: 7
disease_research_center: 0
vaccine_reseach_center: 0
vaccine_center_details:
  gdp_cost: 40765
  health_resource_cost: 20
  human_welfare_resource_cost: 30
  cost_gdp_perstep: 3435
  trickle_set_combo: 4
loci:
  - name: Maharashtra
    B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 19.7515
    lon: 75.7139
    susceptible: 112374333
    infected: 100000
    recovered: 10
    area: 307713
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Chhatrapati Shivaji Maharaj International Airport
        hub_tier: 1
      - name: Pune International Airport
        hub_tier: 2
    ports:
      - name: Mumbai Port
        hub_tier: 1
    economic_zones:
      - name: Mumbai SEZ
        zone_tier: 1
    tourist_zones:
      - name: Gateway of India
        zone_tier: 1
  - name: Delhi
    B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 28.7041
    lon: 77.1025
    susceptible: 16787941
    infected: 100000
    recovered: 10
    area: 1484
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Indira Gandhi International Airport
        hub_tier: 1
    ports:
    economic_zones:
      - name: Delhi SEZ
        zone_tier: 1
    tourist_zones:
      - name: Qutub Minar
        zone_tier: 1
      - name: Red Fort
        zone_tier: 2
  - name: Uttar Pradesh
    B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 26.8467
    lon: 80.9462
    susceptible: 199812341
    infected: 100000
    recovered: 10
    area: 243290
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Chaudhary Charan Singh International Airport
        hub_tier: 1
    ports:
    economic_zones:
      - name: Noida SEZ
        zone_tier: 1
    tourist_zones:
      - name: Taj Mahal
        zone_tier: 1
  - name: Rajasthan
    B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 27.0238
    lon: 74.2179
    susceptible: 68548437
    infected: 100000
    recovered: 10
    area: 342239
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Jaipur International Airport
        hub_tier: 1
    ports:
    economic_zones:
      - name: Jaipur SEZ
        zone_tier: 1
    tourist_zones:
      - name: Jaipur Historical Sites
        zone_tier: 1
      - name: Udaipur Historical Sites
        zone_tier: 2
  - name: Kerala
    B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 10.8505
    lon: 76.2711
    susceptible: 33406061
    infected: 100000
    recovered: 10
    area: 38863
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Cochin International Airport
        hub_tier: 1
    ports:
      - name: Cochin Port
        hub_tier: 1
      - name: Vizhinjam Port
        hub_tier: 2
    economic_zones:
      - name: Cochin SEZ
        zone_tier: 1
    tourist_zones:
      - name: Kerala Backwaters
        zone_tier: 1
      - name: Munnar Tea Estates
        zone_tier: 2
  - name: West Bengal
    B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 22.9868
    lon: 87.8550
    susceptible: 91276115
    infected: 100000
    recovered: 10
    area: 88752
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Netaji Subhas Chandra Bose International Airport
        hub_tier: 1
      - name: Bagdogra Airport
        hub_tier: 2
    ports:
      - name: Kolkata Port
        hub_tier: 1
    economic_zones:
      - name: Kolkata SEZ
        zone_tier: 1
    tourist_zones:
      - name: Victoria Memorial
        zone_tier: 1
  - name: Gujarat
    B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 22.2587
    lon: 71.1924
    susceptible: 60439692
    infected: 100000
    recovered: 10
    area: 196024
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Sardar Vallabhbhai Patel International Airport
        hub_tier: 1
    ports:
      - name: Kandla Port
        hub_tier: 1
    economic_zones:
      - name: Ahmedabad SEZ
        zone_tier: 1
    tourist_zones:
      - name: Sabarmati Ashram
        zone_tier: 1
