name: Japan
gdp: 2875140000
health_resource_stockpile: 50000.0
sanitation_equipment_stockpile: 50000.0
human_welfare_resource: 10000.0
happiness_index: 1.0
procedure_resistance: 0.6
cleanliness_index: 0.7
disease_research_center: 0
vaccine_research_center: 0
vaccines_stock: 
  - name: ABC
    quantity: 20
    gdp_cost_per_step: 1000
    effectiveness: 0.4
  - name: ACB
    quantity: 30
    gdp_cost_per_step: 1000
    effectiveness: 0.22
  - name: BAC
    quantity: 10
    gdp_cost_per_step: 1000
    effectiveness: 0.95
  - name: BCA
    quantity: 12
    gdp_cost_per_step: 1000
    effectiveness: -0.2
  - name: CAB
    quantity: 23
    gdp_cost_per_step: 1000
    effectiveness: 0.5
  - name: CBA
    quantity: 10
    gdp_cost_per_step: 1000
    effectiveness: 0.1
loci:
  - name: Tokyo
    B: 0.01
    C: 0.01
    E: 0.01
    A: 0.01
    Ds: 0.01
    Di: 0.01
    Dr: 0.01
    lat: 19.7515
    lon: 75.7139
    susceptible: 112374333
    infected: 100000
    recovered: 10
    dead: 30
    area: 307713
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Narita International Airport
        hub_tier: 1
        infection_rate : 0.003
        effect: 1.0

      - name: Haneda Airport
        hub_tier: 2
        infection_rate : 0.008
        effect: 1.0

    ports:
      - name: Port of Tokyo
        hub_tier: 1
        infection_rate : 0.0003
        effect: 1.0

      - name: Port of Yokohama
        hub_tier: 1
        infection_rate : 0.0004
        effect: 1.0

    economic_zones:
      - name: Tokyo Bay
        zone_tier: 1
        effect: 1.0
      - name: Shinjuku
        zone_tier: 2
        effect: 1.0
      - name: Shibuya
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Tokyo Tower
        zone_tier: 1
        effect: 1.0
      - name: Tokyo Disneyland
        zone_tier: 2
        effect: 1.0
      - name: Tokyo Skytree
        zone_tier: 2
        effect: 1.0

  - name: Osaka
    B: 0.01
    C: 0.01
    E: 0.01
    A: 0.01
    Ds: 0.01
    Di: 0.01
    Dr: 0.01
    lat: 19.7515
    lon: 75.7139
    susceptible: 112374333
    infected: 100000
    recovered: 10
    dead: 30
    area: 307713
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: Kansai International Airport
        infection_rate : 0.002
        hub_tier: 1
        effect: 1.0
      - name: Osaka International Airport
        hub_tier: 2
        effect: 1.0
        infection_rate : 0.007

    ports:
      - name: Port of Osaka
        hub_tier: 1
        infection_rate : 0.0004
        effect: 1.0


    economic_zones:
      - name: Umeda
        zone_tier: 1
        effect: 1.0
      - name: Namba
        zone_tier: 2
        effect: 1.0
      - name: Tennoji
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Osaka Castle
        zone_tier: 1
        effect: 1.0
      - name: Universal Studios Japan
        zone_tier: 2
        effect: 1.0
      - name: Osaka Aquarium Kaiyukan
        zone_tier: 2
        effect: 1.0

  - name: Sapporo
    B: 0.01
    C: 0.01
    E: 0.01
    A: 0.01
    Ds: 0.01
    Di: 0.01
    Dr: 0.01
    lat: 19.7515
    lon: 75.7139
    susceptible: 112374333
    infected: 100000
    recovered: 10
    dead: 30
    area: 307713
    quarantine_facilities: 2
    general_hospitals: 10
    vaccine_distribution_centers: 0
    airports:
      - name: New Chitose Airport
        hub_tier: 1
        effect: 1.0
        infection_rate : 0.0009

      - name: Okadama Airport
        hub_tier: 2
        effect: 1.0
        infection_rate : 0.0009

    ports:
      - name: Port of Otaru
        hub_tier: 1
        infection_rate : 0.0004
        effect: 1.0

    economic_zones:
      - name: Sapporo Station
        zone_tier: 1
        effect: 1.0
      - name: Susukino
        zone_tier: 2
        effect: 1.0
      - name: Odori Park
        zone_tier: 2
        effect: 1.0
    tourist_zones:
      - name: Sapporo Clock Tower
        zone_tier: 1
        effect: 1.0
      - name: Sapporo TV Tower
        zone_tier: 2
        effect: 1.0
      - name: Moerenuma Park
        zone_tier: 2
        effect: 1.0


