---
name: Pakistan
gdp: 1000000
health_resource_stockpile: 500
sanitation_equipment_stockpile: 20
human_welfare_resource: 100
happiness_index: 1.0
procedure_resistance: 0.6
cleanliness_index: 7
base_death_rate: 0.001
disease_research_center: 0
vaccine_reseach_center: 0
vaccine_center_details:
  gdp_cost: 40765
  health_resource_cost: 20
  human_welfare_resource_cost: 30
  cost_gdp_perstep: 3435
  trickle_set_combo: 4
loci:
  - B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 19.076
    lon: 72.8777
    name: Punjab
    susceptible: 120000000
    infected: 100000
    recovered: 10
    area: 50362
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Allama Iqbal Int. Airport
        hub_tier: 1
      - name: Multan Airport
        hub_tier: 2
      - name: Faisalabad Airport
        hub_tier: 2
    ports:
      - name: Karachi Port
        hub_tier: 1
      - name: Port Qasim
        hub_tier: 1
    economic_zones:
      - name: Lahore SEZ
        zone_tier: 1
      - name: Multan SEZ
        zone_tier: 2
      - name: Faisalabad SEZ
        zone_tier: 2
    tourist_zones:
      - name: Lahore Historical Sites
        zone_tier: 1
      - name: Multan Fort
        zone_tier: 2
  - B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 24.8607
    lon: 67.0011
    name: Sindh
    susceptible: 120000000
    infected: 100000
    recovered: 10
    area: 140914
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Jinnah Int. Airport
        hub_tier: 1
      - name: Hyderabad Airport
        hub_tier: 2
      - name: Sukkur Airport
        hub_tier: 2
    ports:
      - name: Karachi Port
        hub_tier: 1
      - name: Port Qasim
        hub_tier: 1
    economic_zones:
      - name: Karachi SEZ
        zone_tier: 1
      - name: Hyderabad SEZ
        zone_tier: 2
      - name: Sukkur SEZ
        zone_tier: 2
    tourist_zones:
      - name: Karachi Beaches
        zone_tier: 1
      - name: Hyderabad Historical Sites
        zone_tier: 2
  - B: 0.0001
    C: 0.0001
    E: 0.0001
    A: 0.0001
    Ds: 0.0001
    Di: 0.0001
    Dr: 0.0001
    lat: 34.5553
    lon: 72.1285
    name: Khyber Pakhtunkhwa
    susceptible: 120000000
    infected: 100000
    recovered: 10
    area: 101741
    quarantine_facilities: 2
    general_hospitals: 10
    airports:
      - name: Bacha Khan Int. Airport
        hub_tier: 1
      - name: Peshawar Airport
        hub_tier: 2
      - name: Abbottabad Airport
        hub_tier: 2
    ports:
      - name: Gwadar Port
        hub_tier: 1
      - name: Port Qasim
        hub_tier: 1
    economic_zones:
      - name: Peshawar SEZ
        zone_tier: 1
      - name: Abbottabad SEZ
        zone_tier: 2
      - name: Mardan SEZ
        zone_tier: 2
    tourist_zones:
      - name: Peshawar Historical Sites
        zone_tier: 1
      - name: Abbottabad Hill Station
        zone_tier: 2
